---
- name: Install Apache Tomcat8.5.81 using ansible
  hosts: node1
  remote_user: devops
  become: true
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
 
    - name: Create a Tomcat User
      user:
        name: tomcat
 
    - name: Create a Tomcat Group
      group:
        name: tomcat
 
    - name: Create a Tomcat Directory
      file:
        path: /opt/tomcat8
        owner: tomcat
        group: tomcat
        mode: 755
        recurse: yes

    - name: Copying the Directory and its contents
      copy:
        src: ~/installer/apache-tomcat-8.5.81.tar.gz
        dest: /tmp

    - name: Unarchive tomcat8 on the remote server
      unarchive:
        src: /tmp/apache-tomcat-8.5.81.tar.gz
        dest: /opt/tomcat8
        remote_src: yes
        extra_opts: [--strip-components=1]
      
    - name: Change ownership of tomcat directory
      file:
        path: /opt/tomcat8
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
 
    - name: Copy Tomcat service from local to remote
      copy:
        src: ~/installer/tomcat.service
        dest: /etc/systemd/system/
        mode: 0755
 
    - name: Start and Enable Tomcat8 on sever
      systemd:
        name: tomcat
        state: started
        daemon_reload: true