---
- name: Enable internet services
  hosts: node2
  become: true
  tasks: 
    - name: latest version of all required packages installed
      yum:
        name:
          - firewalld
          - httpd
          - mariadb-server
          - php
          - php-mysqlnd
        state: latest

    - name: firewalld is enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started

    - name: mariadb enabled and running
      service:
        name: mariadb
        enabled: true
        state: started

    - name: test php page is installed
      get_url:
        url: "https://www.php.net/manual/en/tutorial.firstpage.php"
        dest: /var/www/html/index.php
        mode: 0644        

- name: Test internet web server
  hosts: localhost
  become: no
  tasks:
    - name: connect to internet web server
      uri:
        url: http://node2
        status_code: 200
